ProjectX/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjectX.BLL.Interfaces;
using ProjectX.BLL.Models;
using ProjectX.MVC.ViewModel;

namespace ProjectX.MVC.Controllers
{
    [Authorize(Roles = "manager")]
    public class GroupsController : Controller
    {
        private readonly IGroupService _groupService;
        private readonly IMapper _mapper;
        private readonly ILogger<GroupsController> _logger;
        private readonly IEntityService<Teacher> _teacherService;
        private readonly IEntityService<Course> _courseService;
        public GroupsController(IGroupService groupService, IEntityService<Teacher> teacherService, 
            IEntityService<Course> courseService, IMapper mapper, ILogger<GroupsController> logger)
        {
            _mapper = mapper;
            _logger = logger;
            _groupService = groupService;
            _teacherService = teacherService;
            _courseService = courseService;
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                return View(_mapper.Map<IEnumerable<GroupViewModel>>(await _groupService.GetAllAsync()));
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                ViewBag.Teachers = _mapper.Map<IEnumerable<TeacherViewModel>>( await _teacherService.GetAllAsync());
                ViewBag.Courses = _mapper.Map<IEnumerable<CourseViewModel>>(await _courseService.GetAllAsync());
                return View(id.HasValue
                    ? _mapper.Map<GroupViewModel>(_groupService.GetGroup(id.Value))
                    : new GroupViewModel());
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(GroupViewModel group)
        {
            try
            {
                ViewBag.Teachers = _mapper.Map<IEnumerable<TeacherViewModel>>(await _teacherService.GetAllAsync());
                ViewBag.Courses = _mapper.Map<IEnumerable<CourseViewModel>>(await _courseService.GetAllAsync());
                if (!ModelState.IsValid)
                    return View(group);

                if (group.Id != 0)
                    _groupService.Update(_mapper.Map<Group>(group));
                else
                    _groupService.Create(_mapper.Map<Group>(group));

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            try
            {
                _groupService.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

ProjectX/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjectX.BLL.Interfaces;
using ProjectX.BLL.Models;
using ProjectX.MVC.ViewModel;

namespace ProjectX.MVC.Controllers
{
    [Authorize(Roles = "manager")]
    public class StudentsController : Controller
    {
        private readonly IStudentService _studentService;
        private readonly IGroupService _groupService;
        private readonly IMapper _mapper;
        private readonly ILogger<StudentsController> _logger;
        public StudentsController(IStudentService studentService, IGroupService groupService,
            IMapper mapper, ILogger<StudentsController> logger)
        {
            _mapper = mapper;
            _logger = logger;
            _studentService = studentService;
            _groupService = groupService;
        }

        public async Task<IActionResult> Index(int? id)
        {
            try
            {
                var students = await _studentService.GetAllAsync();
                return View(id.HasValue 
                    ? _mapper.Map<IEnumerable<StudentViewModel>>(students.Where(_ => _.GroupId == id))
                    : _mapper.Map<IEnumerable<StudentViewModel>>(students));
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                ViewBag.Groups = _mapper.Map<IEnumerable<GroupViewModel>>(await _groupService.GetAllAsync());
                return View(id.HasValue
                    ? _mapper.Map<StudentViewModel>(_studentService.GetStudent(id.Value))
                    : new StudentViewModel());
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(StudentViewModel student)
        {
            try
            {
                ViewBag.Groups = _mapper.Map<IEnumerable<GroupViewModel>>(await _groupService.GetAllAsync());
                if (!ModelState.IsValid)
                    return View(student);

                if (student.Id != 0)
                    _studentService.Update(_mapper.Map<Student>(student));
                else
                    _studentService.Create(_mapper.Map<Student>(student));

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            try
            {
                _studentService.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

ProjectX/Views/Groups/Edit.cshtml
@using ProjectX.MVC.ViewModel;
@{
    var statusesList = new Dictionary<int, string>
    {
        [0] = "Pending",
        [1] = "Started",
        [2] = "Finished"
    };

}
@model GroupViewModel

<div class="row align-items-center" >
    <div class="card shadow widthEditCard" >
        <div class="card-header  py-3">
            <h2 class="text-center m-0 font-weight-bold">Edit group</h2>
            <form asp-action="Edit" method="post">
                <div>
                    <div class="form-group">
                        <label asp-for="Number"></label>
                        <input asp-for="Number" class="form-control" />
                        <span class="alert-danger" asp-validation-for="Number"></span>
                    </div>
                    <div class="form-group">
                        <label class="my-1 mr-2" for="inlineFormCustomSelectPref1">Course</label>
                        <select asp-for="CourseId" class="form-control" id="inlineFormCustomSelectPref1">
                            <option selected value="">Choose...</option>
                            @foreach (CourseViewModel course in ViewBag.Courses)
                            {
                                <option value="@course.Id">@course.Title</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="my-1 mr-2" for="inlineFormCustomSelectPref2">Teacher</label>
                        <select asp-for="TeacherId" class="form-control" id="inlineFormCustomSelectPref2">
                            <option selected value="">Choose...</option>
                            @foreach (TeacherViewModel teacher in ViewBag.Teachers)
                            {
                                <option value="@teacher.Id">@teacher.FullName</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="StartDate"></label>
                        <input asp-for="StartDate" id="hire-date" class="form-control" type="date">
                    </div>
                    <div class="form-group">
                        <label class="my-1 mr-2" for="inlineFormCustomSelectPref3">Status</label>
                        <select asp-for="Status" class="form-control" id="inlineFormCustomSelectPref3" novalidate>
                            <option selected value="">Choose...</option>
                            @foreach (var status in statusesList)
                            {
                                <option value="@status.Key">@status.Value</option>
                            }
                        </select>
                    </div>
                    <div class="text-center">
                        <button class="btn btn-primary" type="submit">Save</button>
                        <a class="btn btn-secondary" area-hidden="true" asp-action="Index">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts
{
    @await Html.PartialAsync("_ValidationScriptsPartial.cshtml")
}

ProjectX/Views/Groups/Index.cshtml
@using ProjectX.MVC.ViewModel
@{
}
@model IEnumerable<GroupViewModel>

<div class="container-fluid widthInfoCard">
    <div class="card shadow">
        <div class="card-header py-3">
            <h2 class="text-center m-0 font-weight-bold">Groups Info</h2>
        </div>
        <a asp-controller="Groups" asp-action ="Edit" class="btn btn-success">Add new group</a>
        <div class="card-body custom-font-size-group-table">
            <div class="table-responsive table mt-2" role="grid" aria-describedby="dataTable_info">
                <table class="table-hover my-0" id="dataTable">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Number</th>
                            <th>Course</th>
                            <th>Teacher</th>
                            <th>StartDate</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var group in Model)
                        {
                        <tr>
                            <td>@group.Id</td>
                            <td>@group.Number</td>
                            @if (group.CourseId != null)
                            {
                                <td>@group.Course.Title</td>
                            }
                            else
                            {
                                <td></td>
                            }
                            @if (group.TeacherName != null)
                            {
                                <td>@group.TeacherName</td>
                            }
                            else
                            {
                                <td></td>
                            }
                            <td>@group.StartDate.Day.@group.StartDate.Month.@group.StartDate.Year</td>
                            <td>@group.Status.ToString()</td>
                            <td>
                                <a asp-controller="Students" asp-action="Index" asp-route-id="@group.Id" class="btn btn-outline-info">View</a>
                            </td>
                            <td>
                                <a asp-controller="Groups" asp-action="Edit" asp-route-id="@group.Id" class="btn btn-outline-primary">Edit</a>
                            </td>
                            <td>
                                <form asp-action="Delete" method="post">
                                    <input type="hidden" name="id" value="@group.Id" />
                                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td>
                                <div class="text-info">Total: @Model.Count()</div>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>