ProjectX/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjectX.BLL.Interfaces;
using ProjectX.BLL.Models;
using ProjectX.MVC.ViewModel;

namespace ProjectX.MVC.Controllers
{
    public class CoursesController : Controller
    {
        private readonly IEntityService<Specialization> _specializationService;
        private readonly IEntityService<Course> _courseService;
        private readonly IMapper _mapper;
        private readonly ILogger<CoursesController> _logger;
        public CoursesController(IEntityService<Course> courseService, 
            IEntityService<Specialization> specializationService, 
            IMapper mapper, ILogger<CoursesController> logger)
        {
            _specializationService = specializationService;
            _courseService = courseService;
            _mapper = mapper;
            _logger = logger;
        }
        public async Task<IActionResult> Index(int id)
        {
            try
            {
                ViewBag.SpecializationTitle = _specializationService.GetEntityById(id).Title;
                var courses = await _courseService.GetAllAsync();
                return View(_mapper
                    .Map<IEnumerable<CourseViewModel>>(courses.Where(_ => _.SpecializationId == id)).ToList());
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

ProjectX/Controllers/RequestsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjectX.BLL.Enums;
using ProjectX.BLL.Interfaces;
using ProjectX.BLL.Models;
using ProjectX.MVC.ViewModel;

namespace ProjectX.MVC.Controllers
{
    public class RequestsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ILogger<RequestsController> _logger;
        private readonly IStudentService _studentService;
        private readonly IEntityService<Course> _courseService;
        private readonly IStudentRequestService _studentRequestService;
        private readonly RequestsListViewModel _requests;
        private readonly IGroupService _groupService;

        public RequestsController(IStudentRequestService studentRequestsService,
            IStudentService studentService, IEntityService<Course> courseService,
            IMapper mapper, ILogger<RequestsController> logger, RequestsListViewModel requests, IGroupService groupService)
        {
            _groupService = groupService;
            _requests = requests;
            _requests.RequestsList = new List<StudentRequestViewModel>();
            _mapper = mapper;
            _logger = logger;
            _courseService = courseService;
            _studentService = studentService;
            _studentRequestService = studentRequestsService;
        }
        [HttpGet]
        [Authorize(Roles = "manager")]
        public async Task<IActionResult> Index(int? id)
        {
            try
            {
                var requests = await _studentRequestService.GetAllAsync();
                var coursesForDropMenu = new Dictionary<int, string>();
                var studentRequests = requests.ToList();
                foreach (var course in studentRequests.Select(_ => _.Course))
                {
                    coursesForDropMenu[course.Id] = course.Title;
                }
                ViewBag.Courses = coursesForDropMenu;
                if (id.HasValue && id != 0)
                {
                    foreach (var request in _mapper.Map<IEnumerable<StudentRequestViewModel>>(studentRequests.Where(_ => _.CourseId == id)))
                    {
                        _requests.RequestsList.Add(request);
                    }

                    var groups = _mapper.Map<IEnumerable<GroupViewModel>>(await _groupService.GetAllAsync()).Where(g => g.CourseId == id);

                    if (groups.Count() != 0)
                    {
                        ViewBag.Groups = groups;
                        ViewBag.GroupExists = true;
                        ViewBag.CheckingAllowed = true;
                        return View(_requests);
                    }
                    else
                    {
                        ViewBag.CheckingAllowed = true;
                        ViewBag.GroupExists = false;
                        return View(_requests);
                    }
                  
                    


                  
                }
                foreach (var request in _mapper.Map<IEnumerable<StudentRequestViewModel>>(studentRequests))
                {
                    _requests.RequestsList.Add(request);
                }
                ViewBag.CheckingAllowed = false;
                return View(_requests);
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Index(RequestsListViewModel model)
        {
            try
            {
                var requests = _mapper.Map<IEnumerable<StudentRequest>>(model.RequestsList.Where(r => r.Selected));


                _studentRequestService.AssignRequestToGroups(requests, model.GroupId);

                int i = 0;

                return RedirectToAction("Index", "Groups");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }

        }
        [HttpGet]
        [Authorize(Roles = "manager")]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                ViewBag.Courses = _mapper.Map<IEnumerable<CourseViewModel>>(await _courseService.GetAllAsync());
                ViewBag.Students = _mapper.Map<IEnumerable<StudentViewModel>>(await _studentService.GetAllAsync());
                return View(id.HasValue
                    ? _mapper.Map<StudentRequestViewModel>(_studentRequestService.GetEntityById(id.Value))
                    : new StudentRequestViewModel() { Created = null });
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(StudentRequestViewModel studentRequest)
        {
            try
            {
                ViewBag.CoursesSelected = false;
                ViewBag.Courses = _mapper.Map<IEnumerable<CourseViewModel>>(await _courseService.GetAllAsync());
                ViewBag.Students = _mapper.Map<IEnumerable<StudentViewModel>>(await _studentService.GetAllAsync());
                if (studentRequest.Created == null)
                {
                    studentRequest.Created = DateTime.Now;
                }
                if (!ModelState.IsValid)
                    if (studentRequest.Id == 0)
                        return View(new StudentRequestViewModel());
                    else
                        return View(studentRequest);
                if (studentRequest.Id != 0)
                    _studentRequestService.Update(_mapper.Map<StudentRequest>(studentRequest));
                else
                    _studentRequestService.Create(_mapper.Map<StudentRequest>(studentRequest));

                if (User.IsInRole("manager"))
                {
                    return RedirectToAction("RequestsForCourses");
                }
                return RedirectToAction("Index", "Specializations");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditFromQuery(int id)
        {
            try
            {
                ViewBag.CourseName = _courseService.GetEntityById(id).Title;
                ViewBag.Courses = _mapper.Map<IEnumerable<CourseViewModel>>(await _courseService.GetAllAsync());
                ViewBag.Students = _mapper.Map<IEnumerable<StudentViewModel>>(await _studentService.GetAllAsync());
                return View("Edit", new StudentRequestViewModel() { Created = null, CourseId = id });
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        [Authorize(Roles = "manager")]
        public IActionResult Delete(int id)
        {
            try
            {
                _studentRequestService.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }


        [HttpGet]
        [Authorize(Roles = "manager")]
        public async Task<IActionResult> RequestsForCourses(int? id)
        {
            try
            {
                var requests = _mapper.Map<IEnumerable<StudentRequestViewModel>>(await _studentRequestService.GetAllAsync()).ToList();
                var courses = _mapper.Map<IEnumerable<CourseViewModel>>(await _courseService.GetAllAsync()).ToList();
                var allRequestsCount = 0;
                foreach (var course in courses)
                {
                    var count = requests.Count(r => r.CourseId == course.Id);
                    allRequestsCount += count;
                    course.RequestsCount = count;
                }
                ViewBag.RequestsCount = allRequestsCount;
                return View(courses.Where(c => c.RequestsCount != 0));
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

ProjectX/Views/Requests/Edit.cshtml
@using ProjectX.MVC.ViewModel;
@{
    var courseName = ViewBag.CourseName;
    var managerCreateRequest = Model.Id == 0 & Model.CourseId == 0;
    var managerEditRequest = Model.Id != 0 & Model.CourseId != 0;
    var managerEditRequestSecondVariant = Model.Id != 0 & Model.CourseId == 0;
    var studentCreateRequest = Model.Id == 0 & Model.CourseId != 0;
    var headerText = string.Empty;
    var studentTypeList = new Dictionary<int, string>
    {
        [0] = "Online",
        [1] = "Offline",
        [2] = "Mix"
    };
    
}
@model StudentRequestViewModel

<div class="row align-items-center">
    <div class="card shadow widthEditCard">
        <div class="card-header  py-3">
            @if (managerCreateRequest)
            {
                headerText = "Create request";
            }
            else if (studentCreateRequest)
            {
                headerText = $"Your application for the course {courseName.ToString()}";
            }
            else if(managerEditRequest)
            {
                headerText = "Edit request";
            }
            <h2 class="text-center m-0 font-weight-bold">@headerText</h2>
            <form asp-action="Edit" method="post">
                <div>
                    @Html.HiddenFor(m => m.Created)
                    <div class="form-group">
                        <label asp-for="FirstName"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span class="alert-danger" asp-validation-for="FirstName"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span class="alert-danger" asp-validation-for="LastName"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Phone"></label>
                        <input asp-for="Phone" class="form-control" />
                        <span class="alert-danger" asp-validation-for="Phone"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email"></label>
                        <input asp-for="Email" class="form-control" />
                        <span class="alert-danger" asp-validation-for="Phone"></span>
                    </div>
                    @if (managerCreateRequest || managerEditRequest|| managerEditRequestSecondVariant)
                    {
                <div class="form-group">
                    <label class="my-1 mr-2" for="inlineFormCustomSelectPref1">Course</label>
                    <select asp-for="CourseId" class="form-control" id="inlineFormCustomSelectPref1">
                        @if(managerCreateRequest)
                        {
                            <option selected value="">Choose...</option>
                           
                        }
                        @foreach (CourseViewModel course in ViewBag.Courses)
                        {
                            <option value="@course.Id">@course.Title</option>
                        }
                    </select>
                    <span class="alert-danger" asp-validation-for="CourseId"></span>
                </div>
                    }
                    @Html.HiddenFor(m => m.CourseId)
                    <div class="form-group">
                        <label class="my-1 mr-2" for="inlineFormCustomSelectPref2">Type of Training</label>
                        <select asp-for="Type" class="form-control" id="inlineFormCustomSelectPref2">
                            <option selected value="">Choose...</option>
                            @foreach (var type in studentTypeList)
                            {
                                <option value="@type.Key">@type.Value</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Comments"></label>
                        <textarea class="form-control" rows="3" asp-for="Comments"></textarea>
                        <span class="alert-danger" asp-validation-for="Comments"></span>
                    </div>
                    <div class="text-center">
                        <button class="btn btn-primary" type="submit">Save</button>
                        @if (studentCreateRequest)
                        {
                            <a class="btn btn-secondary" asp-controller="Courses" asp-action="Index">Save</a>
                        }
                        else
                        {
                            <a class="btn btn-secondary" asp-action="Index">Cancel</a>
                        }
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial.cshtml")
}

ProjectX/Views/Requests/Index.cshtml
@using ProjectX.MVC.ViewModel
@using System.Linq
@using System.Runtime.InteropServices.ComTypes
@{
    Dictionary<int, string> coursesForDropMenu = ViewBag.Courses;
}
@model RequestsListViewModel
<div class="container-fluid widthInfoCard">
    <div class="card shadow">
        <div class="card-header py-3">
            <h2 class="text-center m-0 font-weight-bold">Requests Info</h2>
        </div>
        <a asp-controller="Requests" asp-action="Edit" class="btn btn-success">Add new student request</a>
        <form asp-controller="Requests" asp-action="Index" method="post">
            <div class="card-body  custom-font-size">
                <div class="table-responsive  custom-table-height table mt-2" role="grid" aria-describedby="dataTable_info">
                    <table class="custom-vertical-align custom-table-width table-hover my-0" id="dataTable">
                        <tr>
                            @if ((bool)ViewBag.CheckingAllowed && (bool)ViewBag.GroupExists)
                            {
                                <th>Check</th>
                            }
                            <th>Created</th>
                            <th>Last Name</th>
                            <th>First Name</th>
                            <th>Phone</th>
                            <th>Email</th>
                            <th>
                                <nav class="navbar custom-padding custom-color navbar-expand-md navigation-clean-button">
                                    <ul class="nav navbar-nav mr-auto">
                                        <li class="nav-item dropdown">
                                            <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Sort by course</a>
                                            <div class="dropdown-menu custom-margin" role="menu">
                                                @foreach (var course in coursesForDropMenu)
                                                {
                                                    <a class="dropdown-item-text custom-color" role="presentation" asp-controller="Requests" asp-action="Index" asp-route-id="@course.Key">@course.Value</a>
                                                }
                                            </div>
                                        </li>
                                    </ul>
                                </nav>
                            </th>
                            <th>Type of Training</th>
                            <th>Comments</th>
                            @if ((bool)ViewBag.CheckingAllowed && (bool)ViewBag.GroupExists)
                            {
                                <th class="custom-width">
                                    <nav class="navbar navbar-light navbar-expand-md navigation-clean-button">
                                        <div>
                                            <div class="collapse navbar-collapse" id="navcol-1">

                                                <span class="navbar-text actions">
                                                    <button type="submit" class="btn btn-light bg-success shadow-sm action-button" role="button">Add student(s) to group</button>
                                                </span>
                                            </div>
                                            <span class="custom-dropdown small">
                                                <select asp-for="GroupId">
                                                    <option value="hide">-- Group number --</option>
                                                    @foreach (GroupViewModel group in ViewBag.Groups)
                                                    {
                                                        <option value="@group.Id">@group.Number @group.Status</option>
                                                    }
                                                </select>
                                            </span>
                                        </div>
                                    </nav>
                                </th>
                            }
                            else
                            {
                                <th class="custom-width">
                                    <nav class="navbar navbar-light navbar-expand-md navigation-clean-button">
                                        <div class="row">
                                            <div class="collapse navbar-collapse" id="navcol-1">
                                                <span class="navbar-text actions">
                                                    <a asp-controller="Groups" asp-action="Edit" 
                                                       class="btn btn-light bg-danger shadow-sm action-button" role="button">Create new group</a>
                                                </span>
                                            </div>
                                        </div>
                                    </nav>
                                </th>
                            }
                        </tr>
                        @for (int i = 0; i < Model.RequestsList.Count; i++)
                        {
                            <tr>

                                @Html.HiddenFor(m => m.RequestsList[i].Id)
                                @if ((bool)ViewBag.CheckingAllowed && (bool)ViewBag.GroupExists)
                                {
                                    <td>
                                        @Html.EditorFor(m => m.RequestsList[i].Selected)
                                    </td>
                                }
                                <td>
                                    @Model.RequestsList[i].Created
                                    @Html.HiddenFor(m => m.RequestsList[i].Created)
                                </td>
                                <td>
                                    @Model.RequestsList[i].LastName
                                    @Html.HiddenFor(m => m.RequestsList[i].LastName)
                                </td>
                                <td>
                                    @Model.RequestsList[i].FirstName
                                    @Html.HiddenFor(m => m.RequestsList[i].FirstName)
                                </td>
                                <td>
                                    @Model.RequestsList[i].Phone
                                    @Html.HiddenFor(m => m.RequestsList[i].Phone)
                                </td>
                                <td>
                                    @Model.RequestsList[i].Email
                                    @Html.HiddenFor(m => m.RequestsList[i].Email)
                                </td>
                                @Html.HiddenFor(m => m.RequestsList[i].CourseId)
                                <td>
                                    @Model.RequestsList[i].Course.Title
                                    @Html.HiddenFor(m => m.RequestsList[i].Course.Title)
                                </td>
                                <td>
                                    @Model.RequestsList[i].Type.ToString()
                                    @Html.HiddenFor(m => m.RequestsList[i].Type)
                                </td>
                                <td>
                                    @Model.RequestsList[i].Comments
                                    @Html.HiddenFor(m => m.RequestsList[i].Comments)
                                </td>
                                <td class="custom-width">
                                    <nav class="navbar navbar-light navbar-expand-md navigation-clean-button">
                                        <div class="row">
                                            <div class="collapse navbar-collapse" id="navcol-1">
                                                <span class="navbar-text actions">
                                                    <a asp-controller="Requests" asp-action="Edit" asp-route-id="@Model.RequestsList[i].Id"
                                                       class="btn btn-light bg-warning shadow-sm action-button" role="button">Edit request</a>
                                                </span>
                                                <span class="navbar-text actions">
                                                    <button asp-controller="Requests" asp-action="Delete" type="submit"
                                                            asp-route-id="@Model.RequestsList[i].Id" class="btn btn-light bg-secondary shadow-sm action-button"
                                                            role="button">
                                                        Delete
                                                    </button>
                                                </span>
                                            </div>
                                        </div>
                                    </nav>
                                </td>
                            </tr>
                        }
                        <tr>
                            <td>
                                <div class="text-info">Total: @Model.RequestsList.Count()</div>
                            </td>
                        </tr>

                    </table>
                </div>
            </div>
        </form>
    </div>
</div>

ProjectX/Views/Requests/RequestsForCourses.cshtml
@using ProjectX.MVC.ViewModel
@using System.Linq
@{

}
@model IEnumerable<CourseViewModel>
<div class="container-fluid widthInfoCard">
    <div class="card shadow">
        <div class="card-header py-3">
            <h2 class="text-center m-0 font-weight-bold">Requests Info</h2>
        </div>
        <a asp-controller="Requests" asp-action="Edit" class="btn btn-success">Add new student request</a>
        <form asp-controller="Requests" asp-action="Index" method="post">
            <div class="card-body">
                <div class="table-responsive custom-table-height table mt-2" role="grid" aria-describedby="dataTable_info">
                    <table class="custom-vertical-align custom-table-width table-hover my-0" id="dataTable">
                        <tr>
                            <th>Course</th>
                            <th>Requests</th>
                        </tr>
                        @foreach (var course in Model)
                        {
                            <tr>
                                <td>
                                    @course.Title
                                </td>
                                <td>
                                    @course.RequestsCount
                                </td>
                                <td class="custom-width">
                                    <nav class="navbar navbar-light navbar-expand-md navigation-clean-button">
                                        <div class="row">
                                            <div class="collapse navbar-collapse" id="navcol-1">
                                                <span class="navbar-text actions">
                                                    <a asp-controller="Requests" asp-action="Index" asp-route-id="@course.Id"
                                                        class="btn btn-light bg-warning shadow-sm action-button" role="button">View requests</a>
                                                </span>
                                            </div>
                                        </div>
                                    </nav>
                                </td>
                            </tr>
                        }
                        <tr>
                            <td>
                                <div class="text-info">Total: @ViewBag.RequestsCount</div>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </form>
    </div>
</div>

ProjectX/Views/Requests/SelectGroupOrCreate.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}