ProjectX/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjectX.BLL.Interfaces;
using ProjectX.BLL.Models;
using ProjectX.MVC.ViewModel;

namespace ProjectX.MVC.Controllers
{
    [Authorize(Roles = "manager")]
    public class GroupsController : Controller
    {
        private readonly IGroupService _groupService;
        private readonly IMapper _mapper;
        private readonly ILogger<GroupsController> _logger;
        private readonly IEntityService<Teacher> _teacherService;
        private readonly IEntityService<Course> _courseService;
        public GroupsController(IGroupService groupService, IEntityService<Teacher> teacherService, 
            IEntityService<Course> courseService, IMapper mapper, ILogger<GroupsController> logger)
        {
            _mapper = mapper;
            _logger = logger;
            _groupService = groupService;
            _teacherService = teacherService;
            _courseService = courseService;
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                return View(_mapper.Map<IEnumerable<GroupViewModel>>(await _groupService.GetAllAsync()));
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                ViewBag.Teachers = _mapper.Map<IEnumerable<TeacherViewModel>>( await _teacherService.GetAllAsync());
                ViewBag.Courses = _mapper.Map<IEnumerable<CourseViewModel>>(await _courseService.GetAllAsync());
                return View(id.HasValue
                    ? _mapper.Map<GroupViewModel>(_groupService.GetGroup(id.Value))
                    : new GroupViewModel());
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(GroupViewModel group)
        {
            try
            {
                ViewBag.Teachers = _mapper.Map<IEnumerable<TeacherViewModel>>(await _teacherService.GetAllAsync());
                ViewBag.Courses = _mapper.Map<IEnumerable<CourseViewModel>>(await _courseService.GetAllAsync());
                if (!ModelState.IsValid)
                    return View(group);

                if (group.Id != 0)
                    _groupService.Update(_mapper.Map<Group>(group));
                else
                    _groupService.Create(_mapper.Map<Group>(group));

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            try
            {
                _groupService.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

ProjectX/Controllers/RequestsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjectX.BLL.Enums;
using ProjectX.BLL.Interfaces;
using ProjectX.BLL.Models;
using ProjectX.MVC.ViewModel;

namespace ProjectX.MVC.Controllers
{
    public class RequestsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ILogger<RequestsController> _logger;
        private readonly IStudentService _studentService;
        private readonly IEntityService<Course> _courseService;
        private readonly IStudentRequestService _studentRequestService;
        private readonly RequestsListViewModel _requests;
        private readonly IGroupService _groupService;

        public RequestsController(IStudentRequestService studentRequestsService,
            IStudentService studentService, IEntityService<Course> courseService,
            IMapper mapper, ILogger<RequestsController> logger, RequestsListViewModel requests, IGroupService groupService)
        {
            _groupService = groupService;
            _requests = requests;
            _requests.RequestsList = new List<StudentRequestViewModel>();
            _mapper = mapper;
            _logger = logger;
            _courseService = courseService;
            _studentService = studentService;
            _studentRequestService = studentRequestsService;
        }
        [HttpGet]
        [Authorize(Roles = "manager")]
        public async Task<IActionResult> Index(int? id)
        {
            try
            {
                var requests = await _studentRequestService.GetAllAsync();
                var coursesForDropMenu = new Dictionary<int, string>();
                var studentRequests = requests.ToList();
                foreach (var course in studentRequests.Select(_ => _.Course))
                {
                    coursesForDropMenu[course.Id] = course.Title;
                }
                ViewBag.Courses = coursesForDropMenu;
                if (id.HasValue && id != 0)
                {
                    foreach (var request in _mapper.Map<IEnumerable<StudentRequestViewModel>>(studentRequests.Where(_ => _.CourseId == id)))
                    {
                        _requests.RequestsList.Add(request);
                    }

                    var groups = _mapper.Map<IEnumerable<GroupViewModel>>(await _groupService.GetAllAsync()).Where(g => g.CourseId == id);

                    if (groups.Count() != 0)
                    {
                        ViewBag.Groups = groups;
                        ViewBag.GroupExists = true;
                        ViewBag.CheckingAllowed = true;
                        return View(_requests);
                    }
                    else
                    {
                        ViewBag.CheckingAllowed = true;
                        ViewBag.GroupExists = false;
                        return View(_requests);
                    }
                  
                    


                  
                }
                foreach (var request in _mapper.Map<IEnumerable<StudentRequestViewModel>>(studentRequests))
                {
                    _requests.RequestsList.Add(request);
                }
                ViewBag.CheckingAllowed = false;
                return View(_requests);
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Index(RequestsListViewModel model)
        {
            try
            {
                var requests = _mapper.Map<IEnumerable<StudentRequest>>(model.RequestsList.Where(r => r.Selected));


                _studentRequestService.AssignRequestToGroups(requests, model.GroupId);

                int i = 0;

                return RedirectToAction("Index", "Groups");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }

        }
        [HttpGet]
        [Authorize(Roles = "manager")]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                ViewBag.Courses = _mapper.Map<IEnumerable<CourseViewModel>>(await _courseService.GetAllAsync());
                ViewBag.Students = _mapper.Map<IEnumerable<StudentViewModel>>(await _studentService.GetAllAsync());
                return View(id.HasValue
                    ? _mapper.Map<StudentRequestViewModel>(_studentRequestService.GetEntityById(id.Value))
                    : new StudentRequestViewModel() { Created = null });
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(StudentRequestViewModel studentRequest)
        {
            try
            {
                ViewBag.CoursesSelected = false;
                ViewBag.Courses = _mapper.Map<IEnumerable<CourseViewModel>>(await _courseService.GetAllAsync());
                ViewBag.Students = _mapper.Map<IEnumerable<StudentViewModel>>(await _studentService.GetAllAsync());
                if (studentRequest.Created == null)
                {
                    studentRequest.Created = DateTime.Now;
                }
                if (!ModelState.IsValid)
                    if (studentRequest.Id == 0)
                        return View(new StudentRequestViewModel());
                    else
                        return View(studentRequest);
                if (studentRequest.Id != 0)
                    _studentRequestService.Update(_mapper.Map<StudentRequest>(studentRequest));
                else
                    _studentRequestService.Create(_mapper.Map<StudentRequest>(studentRequest));

                if (User.IsInRole("manager"))
                {
                    return RedirectToAction("RequestsForCourses");
                }
                return RedirectToAction("Index", "Specializations");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditFromQuery(int id)
        {
            try
            {
                ViewBag.CourseName = _courseService.GetEntityById(id).Title;
                ViewBag.Courses = _mapper.Map<IEnumerable<CourseViewModel>>(await _courseService.GetAllAsync());
                ViewBag.Students = _mapper.Map<IEnumerable<StudentViewModel>>(await _studentService.GetAllAsync());
                return View("Edit", new StudentRequestViewModel() { Created = null, CourseId = id });
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        [Authorize(Roles = "manager")]
        public IActionResult Delete(int id)
        {
            try
            {
                _studentRequestService.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }


        [HttpGet]
        [Authorize(Roles = "manager")]
        public async Task<IActionResult> RequestsForCourses(int? id)
        {
            try
            {
                var requests = _mapper.Map<IEnumerable<StudentRequestViewModel>>(await _studentRequestService.GetAllAsync()).ToList();
                var courses = _mapper.Map<IEnumerable<CourseViewModel>>(await _courseService.GetAllAsync()).ToList();
                var allRequestsCount = 0;
                foreach (var course in courses)
                {
                    var count = requests.Count(r => r.CourseId == course.Id);
                    allRequestsCount += count;
                    course.RequestsCount = count;
                }
                ViewBag.RequestsCount = allRequestsCount;
                return View(courses.Where(c => c.RequestsCount != 0));
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

ProjectX/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjectX.BLL.Interfaces;
using ProjectX.BLL.Models;
using ProjectX.MVC.ViewModel;

namespace ProjectX.MVC.Controllers
{
    [Authorize(Roles = "manager")]
    public class StudentsController : Controller
    {
        private readonly IStudentService _studentService;
        private readonly IGroupService _groupService;
        private readonly IMapper _mapper;
        private readonly ILogger<StudentsController> _logger;
        public StudentsController(IStudentService studentService, IGroupService groupService,
            IMapper mapper, ILogger<StudentsController> logger)
        {
            _mapper = mapper;
            _logger = logger;
            _studentService = studentService;
            _groupService = groupService;
        }

        public async Task<IActionResult> Index(int? id)
        {
            try
            {
                var students = await _studentService.GetAllAsync();
                return View(id.HasValue 
                    ? _mapper.Map<IEnumerable<StudentViewModel>>(students.Where(_ => _.GroupId == id))
                    : _mapper.Map<IEnumerable<StudentViewModel>>(students));
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                ViewBag.Groups = _mapper.Map<IEnumerable<GroupViewModel>>(await _groupService.GetAllAsync());
                return View(id.HasValue
                    ? _mapper.Map<StudentViewModel>(_studentService.GetStudent(id.Value))
                    : new StudentViewModel());
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(StudentViewModel student)
        {
            try
            {
                ViewBag.Groups = _mapper.Map<IEnumerable<GroupViewModel>>(await _groupService.GetAllAsync());
                if (!ModelState.IsValid)
                    return View(student);

                if (student.Id != 0)
                    _studentService.Update(_mapper.Map<Student>(student));
                else
                    _studentService.Create(_mapper.Map<Student>(student));

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            try
            {
                _studentService.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

ProjectX/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ProjectX</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
    <link href="~/assets/css/Navigation-with-Button.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/assets/fonts/fontawesome-all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/css/swiper.min.css">
    <link rel="stylesheet" href="~/assets/css/sidebar.css">

</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-light navbar-expand sticky-top bg-secondary align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0" style="background-color: rgb(8,8,10);">
            <div class="container-fluid d-flex flex-column p-0">
                <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" asp-area="" asp-controller="Home" asp-action="Index">
                    <div class="sidebar-brand-icon rotate-n-15"><i class="fas fa-cat"></i></div>
                    <div class="sidebar-brand-text mx-3"><span class="d-xl-flex justify-content-xl-center">ProjectX</span></div>
                </a>
                <hr class="sidebar-divider my-0">
                <ul class="nav navbar-nav text-light" id="accordionSidebar">
                    @if (!User.IsInRole("manager"))
                    {
                        <li class="nav-item" role="presentation">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fas fa-home"></i><span>Home</span>
                            </a>
                        </li>

                        <li class="nav-item" role="presentation">
                            <a class="nav-link" asp-area="" asp-controller="Specializations" asp-action="Index">
                                <i class="fas fa-graduation-cap"></i><span>Specializations<br></span>
                            </a>
                        </li>
                        <li class="nav-item" role="presentation">
                            <a class="nav-link" asp-area="" asp-controller="Teachers" asp-action="Index">
                                <i class="fas fa-exclamation-circle"></i><span>Teachers</span>
                            </a>
                        </li>
                        <li class="nav-item" role="presentation">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Error">
                                <i class="fas fa-exclamation-circle"></i><span>Materials</span>
                            </a>
                        </li>
                    }
                    @if (User.IsInRole("manager"))
                    {
                        <li class="nav-item" role="presentation">
                            <a class="nav-link" asp-area="" asp-controller="Requests" asp-action="RequestsForCourses">
                                <i class="fas fa-child"></i><span>Requests<br></span>
                            </a>
                        </li>
                        <li class="nav-item" role="presentation">
                            <a class="nav-link" asp-area="" asp-controller="Groups" asp-action="Index">
                                <i class="fas fa-object-group"></i><span>Groups</span>
                            </a>
                        </li>
                        <li class="nav-item" role="presentation">
                            <a class="nav-link" asp-area="" asp-controller="Students" asp-action="Index">
                                <i class="fas fa-exclamation-circle"></i><span>Students</span>
                            </a>
                        </li>
                        <li class="nav-item" role="presentation">
                            <a class="nav-link" asp-area="" asp-controller="Teachers" asp-action="Index">
                                <i class="fas fa-exclamation-circle"></i><span>Teachers</span>
                            </a>
                        </li>
                        <li class="nav-item" role="presentation">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Error">
                                <i class="fas fa-exclamation-circle"></i><span>Materials</span>
                            </a>
                        </li>
                    }
                </ul>
                <div class="text-center d-none d-md-inline">
                    <button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button>
                </div>
            </div>
        </nav>
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar">
                    <div class="container-fluid">
                        <button class="btn btn-link d-md-none rounded-circle mr-3" id="sidebarToggleTop" type="button"><i class="fas fa-bars"></i></button>
                        <form class="form-inline d-none d-sm-inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                            <div class="input-group">
                                <input class="bg-light form-control border-0 small" type="text" placeholder="Search for ...">
                                <div class="input-group-append"><button class="btn btn-primary py-0" type="button"><i class="fas fa-search"></i></button></div>
                            </div>
                        </form>
                        <partial name="_LoginPartial" />
                    </div>
                </nav>
                <div class=" container-fluid align-items-center">
                    <main role="main" class="pb-3">
                        <div class="row justify-content-center">
                            @RenderBody()
                        </div>
                    </main>
                </div>
            </div>
        </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/assets/js/theme.js"></script>
    <script src="~/assets/js/bs-init.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>