ProjectX/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjectX.BLL.Interfaces;
using ProjectX.BLL.Models;
using ProjectX.MVC.ViewModel;

namespace ProjectX.MVC.Controllers
{
    public class TeachersController : Controller
    {
        private readonly IEntityService<Teacher> _teacherService;
        private readonly IMapper _mapper;
        private readonly ILogger<TeachersController> _logger;
        public TeachersController(IEntityService<Teacher> teacherService,
            IMapper mapper, ILogger<TeachersController> logger)
        {
            _logger = logger;
            _mapper = mapper;
            _teacherService = teacherService;
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                var teachers = _mapper.Map<IEnumerable<TeacherViewModel>>(await _teacherService.GetAllAsync());
                if (User.IsInRole("manager"))
                {
                    return View(teachers);
                }
                return View("IndexFromStudents", teachers);
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }

        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            try
            {
                return View(id.HasValue
                    ? _mapper.Map<TeacherViewModel>(_teacherService.GetEntityById(id.Value))
                    : new TeacherViewModel());
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public IActionResult Edit(TeacherViewModel teacher)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(teacher);
                }
                if (teacher.Id != 0)
                    _teacherService.Update(_mapper.Map<Teacher>(teacher));
                else
                    _teacherService.Create(_mapper.Map<Teacher>(teacher));
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            try
            {
                _teacherService.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

ProjectX/Views/Teachers/Edit.cshtml
@using ProjectX.MVC.ViewModel;
@{
}
@model TeacherViewModel

<div class="align-items-center ">
    <div class="card shadow widthEditCard" >
        <div class="card-header  py-3">
            <h2 class="text-center m-0 font-weight-bold">Edit teacher</h2>
            <form asp-action="Edit" method="post">
                <div>
                    <div class="form-group">
                        <label asp-for="LastName"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span class="alert-danger" asp-validation-for="LastName"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FirstName"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span class="alert-danger" asp-validation-for="FirstName"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email"></label>
                        <input asp-for="Email" class="form-control" />
                        <span class="alert-danger" asp-validation-for="Email"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Phone"></label>
                        <input asp-for="Phone" class="form-control" />
                        <span class="alert-danger" asp-validation-for="Phone"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="WorkExperience"></label>
                        <input asp-for="WorkExperience" class="form-control" />
                        <span class="alert-danger" asp-validation-for="WorkExperience"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio"></label>
                        <textarea class="form-control" rows="3" asp-for="Bio"></textarea>
                        <span class="alert-danger" asp-validation-for="Bio"></span>
                    </div>
                    <div class="text-center">
                        <button class="btn btn-primary" type="submit">Save</button>
                        <a class="btn btn-secondary" asp-action="Index">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial.cshtml")
}

ProjectX/Views/Teachers/Index.cshtml
@using ProjectX.MVC.ViewModel

@model IEnumerable<TeacherViewModel>

<div class="container-fluid widthInfoCard" data-aos="fade-down" data-aos-duration="600">
    <div class="card shadow">
        <div class="card-header py-3">
            <h2 class="text-center m-0 font-weight-bold">Teachers Info</h2>
        </div>
        <a asp-controller="Teachers" asp-action="Edit" class="btn btn-success">Add new teacher</a>
        <div class="card-body custom-font-size">
            <div class="table-responsive table mt-2" role="grid" aria-describedby="dataTable_info">
                <table class="table-hover  my-0" id="dataTable">
                    <tr>
                        <th>ID</th>
                        <th>Last Name</th>
                        <th>First Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Work Experience</th>
                        <th>Bio</th>
                    </tr>
                    @foreach (var teacher in Model)
                    {
                        <tr>
                            <td>@teacher.Id</td>
                            <td>@teacher.LastName</td>
                            <td>@teacher.FirstName</td>
                            <td>@teacher.Email</td>
                            <td>@teacher.Phone</td>
                            <td>@teacher.WorkExperience</td>
                            <td>@teacher.Bio</td>
                            <td>
                                <a asp-controller="Teachers" asp-action="Edit" asp-route-id="@teacher.Id" class="btn btn-outline-primary">Edit</a>
                            </td>
                            <td>
                                <form asp-action="Delete" method="post">
                                    <input type="hidden" name="id" value="@teacher.Id" />
                                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    }
                    <tr>
                        <td>
                            <div class="text-info">Total: @Model.Count()</div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

ProjectX/Views/Teachers/IndexFromStudents.cshtml
@using ProjectX.MVC.ViewModel
@{
    string fade = "left";

}
@model IEnumerable<TeacherViewModel>
<div class="container-fluid widthInfoCard">
    <div class="card shadow">
        <div class="card-header py-3">
            <h2 class="text-center m-0 font-weight-bold">Teachers Info</h2>
        </div>
        <div class="card-body">
            <tr>
                @foreach (var teacher in Model)
                {
                    <th>
                        <div class="media border align-top col-12 p-3" data-aos="fade-@fade" data-aos-duration="900">
                            @{
                                fade = fade == "left" ? "right" : "left";
                            }
                            <img src="@Url.Content($"~/assets/img/{teacher.PNGName}")" class="mr-3 mt-3 rounded-circle" style="width: 60px;">
                            <div class="media-body">
                                <h4>@teacher.FullName</h4>
                                <small><i>WorkExperience: @teacher.WorkExperience</i></small>
                                <h5>Info</h5>
                                <p>@teacher.Bio</p>
                            </div>
                        </div>
                    </th>
                }
            </tr>
        </div>
    </div>
</div>